run:
  timeout: 5m
  go: "1.25"

linters:
  disable-all: true
  enable:
    - govet
    - goimports
    - typecheck
    - ineffassign
    - misspell
    - nakedret
    - unconvert
    - staticcheck
    - unused
    - revive